import { Buffer } from 'buffer'
import { GCDomains, GCLibInSnippets, contact } from '../../config'
import {
  APIEncoding,
  APIVersion,
  DefaultAPIVersion,
  DefaultNetwork,
  NetworkType,
  QRTemplateType
} from '../../types'
import { getBaseUrl } from '../../utils'

export type SnippetHandlerArgs = {
  apiVersion: APIVersion
  network: NetworkType
  encoding: APIEncoding
  input: string
  debug?: boolean
  refAddress?: string
  disableNetworkRouter?: boolean
  /**
   * Optional wallet URL pattern override.
   * When provided, snippet outputs can consistently target a custom wallet base
   * (e.g. local development wallets) while preserving handler response types.
   */
  urlPattern?: string

  /**
   * Optional per-token overrides for snippet templates.
   *
   * Keys can be either:
   * - a key of `snippetTokens` (recommended), e.g. `title`, `twitterUrl`
   * - the raw placeholder string (advanced), e.g. `$#___TITLE___#$`
   *
   * Values are injected as-is (no escaping). For JS-literal tokens
   * (like apiVersion/network/encoding) pass a valid JS literal, e.g. `"2"`.
   */
  snippetArgs?: SnippetArgs
  qrResultType?: 'png' | 'svg'
  outputFile?: string
  template?: QRTemplateType | string
  styles?: string
}

export type SnippetArgs = Partial<
  Record<keyof typeof snippetTokens, string>
> & {
  /**
   * Raw JS object literal used to override the entire `defaultIntents` map.
   * This has higher priority than the default user intent injection.
   *
   * Useful when you want to add comments or additional intent definitions.
   */
  defaultIntents?: string
}

export const snippetTokens = {
  title: '$#___TITLE___#$',
  description: '$#___DESCRIPTION___#$',
  appId: '$#___APP_ID___#$',
  appVersion: '$#___APP_VERSION___#$',
  appYear: '$#___APP_YEAR___#$',
  defaultIntentsBlock: '$#___DEFAULT_INTENTS_BLOCK___#$',
  url: '$#___URL___#$',
  urlPattern: '$#___URL_PATTERN___#$',
  walletBaseUrl: '$#___WALLET_BASE_URL___#$',
  apiVersion: '$#___API_VERSION___#$',
  network: '$#___NETWORK___#$',
  encoding: '$#___ENCODING___#$',
  refAddress: '$#___REF_ADDRESS___#$',
  disableNetworkRouter: '$#___DISABLE_NETWORK_ROUTER___#$',
  gcScript: '$#___GC_SCRIPT___#$',
  origin: '$#___ORIGIN___#$',
  playgroundUrl: '$#___PLAYGROUND_URL___#$',
  twitterUrl: '$#___TWITTER_URL___#$',
  discordUrl: '$#___DISCORD_URL___#$',
  youtubeUrl: '$#___YOUTUBE_URL___#$',
  githubUrl: '$#___GITHUB_URL___#$',
  websiteUrl: '$#___WEBSITE_URL___#$',
  autoGeneratedLinkUrl: '$#___AUTO_GENERATED_LINK_URL___#$',
  autoGeneratedLinkText: '$#___AUTO_GENERATED_LINK_TEXT___#$',
  buttonText: '$#___BUTTON_TEXT___#$',
  encodingsArray: '$#___ENCODINGS_ARRAY___#$',
  selectedEncoding: '$#___SELECTED_ENCODING___#$',
  gcLibBrowserImports: '$#___GC_BROWSER_IMPORTS___#$',
  gcLibNodeJsImports: '$#___GC_NODEJS_IMPORTS___#$'
} as const

const defaultHtmlLikeTitle = 'Cardano Dapp'
const defaultHtmlLikeDescription =
  'Review the action details below and continue in GameChanger Wallet.'
const currentYear = new Date().getFullYear().toString()

const defaultAutoGeneratedLinkUrl =
  'https://www.npmjs.com/package/@gamechanger-finance/gc'
const defaultAutoGeneratedLinkText = 'GC NPM Library'
const defaultButtonText = 'Connect with GC'

const connectIntentDefinition = {
  label: 'Connect wallet',
  description: 'Share public wallet information with this dapp.',
  code: {
    type: 'script',
    title: 'Connect with this dapp?',
    description: 'About to share public wallet information with the dapp.',
    exportAs: 'connect',
    run: {
      name: { type: 'getName' },
      address: { type: 'getCurrentAddress' },
      // spendPubKey: { type: 'getSpendingPublicKey' },
      // stakePubKey: { type: 'getStakingPublicKey' },
      addressInfo: {
        type: 'macro',
        run: "{getAddressInfo(get('cache.address'))}"
      }
    }
  }
}

export const replaceSnippetPlaceholders = (
  template: string,
  replacements: Record<string, string>
) => {
  let output = template.split('\\`').join('`').split('\\${').join('${')
  for (const key of Object.keys(replacements)) {
    output = output.split(key).join(replacements[key])
  }
  const unresolved = output.match(/\$#___[A-Z0-9_]+___#\$/g)
  if (unresolved && unresolved.length > 0) {
    throw new Error(
      `Unresolved snippet placeholders: ${Array.from(new Set(unresolved)).join(
        ', '
      )}`
    )
  }
  return output
}

export const toUtf8DataUri = (mimeType: string, text: string) =>
  `data:${mimeType};charset=utf-8;base64,${Buffer.from(text, 'utf8').toString(
    'base64'
  )}`

export const toJSLiteral = (value?: string) =>
  value === undefined ? 'undefined' : JSON.stringify(value)

export const toBooleanLiteral = (value?: boolean) => (value ? 'true' : 'false')

export const resolveSnippetOrigin = (
  apiVersion?: APIVersion,
  network?: NetworkType
) => GCDomains[apiVersion || DefaultAPIVersion][network || DefaultNetwork]

const ensureTrailingSlash = (value?: string) =>
  value ? (value.endsWith('/') ? value : `${value}/`) : value

/**
 * Applies snippetArgs overrides to an existing placeholder map.
 *
 * This enables complete control over every placeholder defined in snippetTokens.
 */
export const applySnippetArgs = (
  replacements: Record<string, string>,
  snippetArgs?: SnippetArgs
): Record<string, string> => {
  if (!snippetArgs) return replacements
  const next: Record<string, string> = { ...replacements }

  // Highest priority override for the whole defaultIntents map.
  if (typeof snippetArgs.defaultIntents === 'string') {
    next[snippetTokens.defaultIntentsBlock] = snippetArgs.defaultIntents
  }

  for (const [key, value] of Object.entries(snippetArgs)) {
    if (value === undefined || value === null) continue
    if (key === 'defaultIntents') continue
    // Recommended: override by snippetTokens key.
    if ((snippetTokens as any)[key]) {
      next[(snippetTokens as any)[key]] = String(value)
      continue
    }
    // Advanced: override by raw placeholder.
    next[key] = String(value)
  }
  return next
}

export const normalizeHtmlZeroEncoding = (encoding: APIEncoding) => {
  if (encoding === 'base64url') return encoding
  return 'gzip'
}

export const resolveHtmlLikeDappTitle = (_script: any) => {
  // if (script && typeof script.title === 'string' && script.title.trim()) {
  //   return script.title.trim()
  // }
  return defaultHtmlLikeTitle
}
export const resolveHtmlLikeDappDescription = (_script: any) => {
  // if (
  //   script &&
  //   typeof script.description === 'string' &&
  //   script.description.trim()
  // ) {
  //   return script.description.trim()
  // }
  return defaultHtmlLikeDescription
}

export const resolveHtmlLikeTitle = (script: any) => {
  if (script && typeof script.title === 'string' && script.title.trim()) {
    return script.title.trim()
  }
  return defaultHtmlLikeTitle
}

export const resolveHtmlLikeDescription = (script: any) => {
  if (
    script &&
    typeof script.description === 'string' &&
    script.description.trim()
  ) {
    return script.description.trim()
  }
  return defaultHtmlLikeDescription
}

export const buildSnippetAppId = (script: any) => {
  const source =
    script && typeof script.title === 'string' && script.title.trim()
      ? script.title.trim()
      : defaultHtmlLikeTitle
  const slug = source
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+/g, '')
    .replace(/-+$/g, '')
  if (slug) return `gc-dapp-${slug}`
  return 'gc-dapp-example'
}

const indentBlock = (value: string, spaces: number) => {
  const padding = ' '.repeat(spaces)
  return value
    .split('\n')
    .map((line) => `${padding}${line}`)
    .join('\n')
}

const commentOutBlock = (value: string, spaces: number) => {
  const padding = ' '.repeat(spaces)
  return value
    .split('\n')
    .map((line) => `${padding}// ${line}`)
    .join('\n')
}

const formatPropertyLiteral = (
  propertyName: string,
  value: unknown,
  withTrailingComma = false
) => {
  const json = JSON.stringify(value, null, 2).split('\n')
  const lines = [`${propertyName}: ${json[0]}`]
  for (let index = 1; index < json.length; index += 1) {
    lines.push(json[index])
  }
  if (withTrailingComma) {
    lines[lines.length - 1] = lines[lines.length - 1] + ','
  }
  return lines.join('\n')
}

export const buildHtmlLikeDefaultIntentsBlock = (
  script: any,
  snippetArgs?: SnippetArgs
) => {
  // Explicit override wins over the injected user intent.
  const rawOverride =
    typeof snippetArgs?.defaultIntents === 'string'
      ? snippetArgs.defaultIntents
      : typeof snippetArgs?.defaultIntentsBlock === 'string'
      ? snippetArgs.defaultIntentsBlock
      : undefined
  if (rawOverride && rawOverride.trim()) return rawOverride

  const connectBlock = formatPropertyLiteral(
    'connect',
    connectIntentDefinition,
    true
  )
  const userIntentDefinition = {
    label: resolveHtmlLikeTitle(script),
    description: resolveHtmlLikeDescription(script),
    code: script
  }
  const userIntentBlock = formatPropertyLiteral(
    'userIntent',
    userIntentDefinition
  )
  return [
    '{',
    '        // Uncomment the connect intent below to enable the most common wallet connection UX out of the box.',
    '        // Intent-based Cardano dapps do not require a mandatory wallet connection to work.',
    commentOutBlock(connectBlock, 8),
    indentBlock(userIntentBlock, 8),
    '      }'
  ].join('\n')
}

export const buildHtmlLikeReplacements = (
  args: Pick<
    SnippetHandlerArgs,
    | 'apiVersion'
    | 'network'
    | 'encoding'
    | 'refAddress'
    | 'disableNetworkRouter'
    | 'urlPattern'
  >,
  script: any,
  version = '0.0.1',
  snippetArgs?: SnippetArgs
): Record<string, string> => {
  const walletBaseUrl = args?.urlPattern ? getBaseUrl(args.urlPattern) : ''
  const replacements = {
    [snippetTokens.title]: resolveHtmlLikeDappTitle(script),
    [snippetTokens.description]: resolveHtmlLikeDappDescription(script),
    [snippetTokens.appId]: buildSnippetAppId(script),
    [snippetTokens.appVersion]: version,
    [snippetTokens.appYear]: currentYear,
    [snippetTokens.defaultIntentsBlock]: buildHtmlLikeDefaultIntentsBlock(
      script,
      snippetArgs
    ),

    // Runtime defaults for templates that embed handler calls.
    [snippetTokens.gcLibBrowserImports]: GCLibInSnippets.browserOutputs,
    [snippetTokens.apiVersion]: toJSLiteral(args.apiVersion),
    [snippetTokens.network]: toJSLiteral(args.network),
    [snippetTokens.encoding]: toJSLiteral(args.encoding),
    [snippetTokens.refAddress]: toJSLiteral(args.refAddress),
    [snippetTokens.disableNetworkRouter]: toBooleanLiteral(
      args.disableNetworkRouter
    ),
    [snippetTokens.urlPattern]: toJSLiteral(args.urlPattern),
    [snippetTokens.walletBaseUrl]: toJSLiteral(walletBaseUrl || ''),

    // Footer links
    [snippetTokens.twitterUrl]: contact.twitter,
    [snippetTokens.discordUrl]: contact.discord,
    [snippetTokens.youtubeUrl]: contact.youtube,
    [snippetTokens.githubUrl]: contact.github,
    [snippetTokens.websiteUrl]: contact.website,
    [snippetTokens.autoGeneratedLinkUrl]: defaultAutoGeneratedLinkUrl,
    [snippetTokens.autoGeneratedLinkText]: defaultAutoGeneratedLinkText,
    [snippetTokens.buttonText]: defaultButtonText
  }
  return applySnippetArgs(replacements, snippetArgs)
}

export const buildHtmlZeroReplacements = (
  args: SnippetHandlerArgs,
  script: any,
  snippetArgs?: SnippetArgs
): Record<string, string> => {
  const origin = ensureTrailingSlash(
    args?.urlPattern ? getBaseUrl(args.urlPattern) : undefined
  )
  const resolvedOrigin =
    origin || resolveSnippetOrigin(args.apiVersion, args.network)
  const walletBaseUrl = args?.urlPattern ? getBaseUrl(args.urlPattern) : ''

  const replacements = {
    [snippetTokens.title]: resolveHtmlLikeTitle(script),
    [snippetTokens.description]: resolveHtmlLikeDescription(script),
    [snippetTokens.appYear]: currentYear,
    [snippetTokens.apiVersion]: JSON.stringify(args.apiVersion),
    [snippetTokens.network]: JSON.stringify(args.network),
    [snippetTokens.encoding]: JSON.stringify(args.encoding),
    [snippetTokens.selectedEncoding]: JSON.stringify(
      normalizeHtmlZeroEncoding(args.encoding)
    ),
    [snippetTokens.refAddress]: toJSLiteral(args.refAddress),
    [snippetTokens.disableNetworkRouter]: toBooleanLiteral(
      args.disableNetworkRouter
    ),
    [snippetTokens.urlPattern]: toJSLiteral(args.urlPattern),
    [snippetTokens.walletBaseUrl]: toJSLiteral(walletBaseUrl || ''),
    [snippetTokens.gcScript]: JSON.stringify(script, null, 2),
    [snippetTokens.origin]: JSON.stringify(resolvedOrigin),
    // TODO: Normalize all this way in the future!
    // [snippetTokens.playgroundUrl]: JSON.stringify(`${origin}playground`),// fix this one
    [snippetTokens.playgroundUrl]: `${resolvedOrigin}playground`,
    [snippetTokens.twitterUrl]: contact.twitter,
    [snippetTokens.discordUrl]: contact.discord,
    [snippetTokens.youtubeUrl]: contact.youtube,
    [snippetTokens.githubUrl]: contact.github,
    [snippetTokens.websiteUrl]: contact.website,
    [snippetTokens.autoGeneratedLinkUrl]: defaultAutoGeneratedLinkUrl,
    [snippetTokens.autoGeneratedLinkText]: defaultAutoGeneratedLinkText,
    [snippetTokens.encodingsArray]: JSON.stringify(['gzip', 'base64url'])
  }

  return applySnippetArgs(replacements, snippetArgs)
}
