import { snippetTokens } from 'src/handlers/snippet/helpers'
import { QRCodeCorrectLevel } from './styles'

import {
  usageMessage,
  QRRenderTypes,
  GCDomains,
  contact,
  version,
  projectName,
  repositoryUrl,
  DefaultNetwork,
  DefaultAPIVersion,
  DefaultAPIEncodings,
  DefaultQRTemplate,
  DefaultQRTitle,
  DefaultQRSubTitle,
  GCLibInSnippets,
  BuildDataFormats,
  BuildResourceProtocols,
  BuildResourceProtocolCategories,
  DefaultBuildAllowedProtocols,
  DefaultMainFileAppURI,
  BuildOutputMimeType,
  ZipDataUriMimeType,
  TarGzDataUriMimeType,
  GCScriptAPIRefURL,
  GCScriptDocsURL,
  GCScriptSchemaURL,
  GCScriptSchemaRootFile,
  GCScriptSchemaCacheFileName,
  GCScriptSchemaCacheTTLHours
} from '.'

export default {
  version,
  projectName,
  repositoryUrl,
  usageMessage,
  QRRenderTypes,
  GCDomains,
  contact,
  DefaultNetwork,
  DefaultAPIVersion,
  DefaultAPIEncodings,
  DefaultQRTemplate,
  DefaultQRTitle,
  DefaultQRSubTitle,
  GCLibInSnippets,
  BuildDataFormats,
  BuildResourceProtocols,
  BuildResourceProtocolCategories,
  DefaultBuildAllowedProtocols,
  DefaultMainFileAppURI,
  BuildOutputMimeType,
  ZipDataUriMimeType,
  TarGzDataUriMimeType,
  GCScriptAPIRefURL,
  GCScriptDocsURL,
  GCScriptSchemaURL,
  GCScriptSchemaRootFile,
  GCScriptSchemaCacheFileName,
  GCScriptSchemaCacheTTLHours,
  snippetTokens,
  QRCodeCorrectLevel
}
